### ISSUE TITLE
투표하기 구현

### ISSUE THREAD

**Issue by cheonjiyun** [mafia-together/frontend#19]
## Describe
투표하기 구현

## Tasks
- [ ] 미리투표하기에서 누르면 투표 전송

## More
클릭할 때 다른 플레이어가 선택되는 css 오류해결

**Comment by kpeel5839** [comment]
![image](https://github.com/mafia-together/frontend/assets/89840550/97170ac9-9702-43cb-b0dd-e2401878ea56)

투표 전송이라는 의미인가요?

**Comment by cheonjiyun** [comment]
네 맞아요..! 오타났네요 수정했습니다
